name: flutter_application
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  auto_route: ^0.6.9
  cached_network_image: ^2.2.0+1
  cookie_jar: ^1.0.1
  date_format: ^1.0.8
  dio_cookie_manager: ^1.0.0
  extended_image: ^1.3.0
  event_bus: ^1.1.1
  fluro: ^1.7.8
  flutter_easyrefresh: ^2.1.6
  flutter_spinkit: ^4.1.2+1
  flutter_swiper: ^1.1.6
  flutter_webview_plugin: ^0.3.11
  image_picker_saver: ^0.3.0
  image_picker: ^0.6.6+1
  multi_image_picker: ^4.6.7
  image_editor: any
  oktoast: ^2.3.2
  path_provider: ^1.6.24
  package_info: ^0.4.3+2
  permission_handler: ^5.0.1+1
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4
  share: ^0.6.5+4
  url_launcher: ^5.7.10
  loading_more_list: ^1.0.5
  #屏幕适配
  flutter_screenutil: ^1.0.2
  extended_nested_scroll_view: ^0.4.0
  flutter_picker: ^1.1.4
  flutter_icons: ^1.1.0
  #扫描二维码
  qr_flutter: ^3.1.0
  r_scan: ^0.1.4+1
  extended_text: ^4.1.0
  extended_text_field: ^5.0.2
  flui: ^0.9.2
  web_socket_channel: ^1.1.0
  sticky_headers: ^0.1.8+1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
  - assets/images/flutter_logo.png
  - assets/images/bmg.jpg

  fonts:
    - family: myicon
      fonts:
        - asset: assets/fonts/myicon.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
